Agg gcloud cli installation

diff --git a/termux_setup b/termux_setup
--- a/termux_setup
+++ b/termux_setup
@@ -55,6 +55,10 @@ main(){
 	echo ">>> Installing Python 3 ..."
 	echo "# Python is a robust programming and scripting language"
 	install python
+	
+	
+	echo ">>> Installing Google Cloud CLI ..."
+	install_gcloud_cli
 
 
 	echo ">>> Installing Neovim ..."
@@ -83,6 +87,10 @@ main(){
 	sleep $WAITLONG
 
 	bash -c "$(curl -fsSL https://git.io/oh-my-termux)"
+	
+	
+	# Clean up
+	clean_up
 }
 
 
@@ -209,6 +217,41 @@ neovim_plugins()
 }
 
 
+# Get Device 32bit/64bit
+device_64_bit(){
+	cpu=`uname -m`
+	if [[ $cpu == *"64"* ]]
+	then
+		return 0
+	elif [[ $cpu == *"armv7"* ]]
+	then
+		return 1
+	else
+		return 0
+	fi
+}
+
+
+
+# Download and Install Google Cloud CLI
+install_gcloud_cli(){
+	device_64_bit
+	bit64=$?
+	if [ $bit64 -e 0 ]
+	then
+		curl -Lo google-cloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-345.0.0-linux-x86_64.tar.gz
+	else
+		curl -Lo google-cloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-345.0.0-linux-x86.tar.gz
+	fi
+	
+	# Extract .tar.gz file
+	tar -xzf google-cloud.tar.gz
+	
+	# Run installation script
+	./google-cloud-sdk/install.sh
+}
+
+
 
 # Welcome Script
 welcome_script()
@@ -234,6 +277,13 @@ Hacker's Keyboard (https://play.google.com/store/apps/details?id=org.pocketworks
 
 " > ../usr/etc/motd
 	cd -
+}
+
+
+
+# delete downloaded file
+clean_up(){
+	rm google-cloud.tar.gz
 }
 
 
